---
title: "essaysample"
format: html
editor: visual
---

## Freudian Analysis of The Little Mermaid

By Paulina Lopez

In Freud's The Ego and The Id, Freud discusses two types of instincts that make up humans and drive them to make the decisions they make and feel the way they feel in their daily lives. One of them is the Eros Instinct. This instinct is based on the natural sexual instincts to procreate and create more life. It encompasses love and lust but also includes self-preservation instincts and the desire to stay alive. The second type of instinct is the opposite; the death instinct. This instinct is the one that drives humans to cause harm to themselves and others and to end life. 

In The Little Mermaid, two characters portray these two instincts that Freud discusses. The Eros instinct possesses traits of love, passion, and lust. In the movie, the protagonist Ariel turns her life upside down to seek love and life in the world beyond the sea. Her motivations are rooted in the Eros instinct as she travels to the land seeking to make the prince fall in love with her. Ariel does make some decisions relating to the death instinct, such as making the reckless and poorly thought decision of signing the deal with Ursula. But even then, her recklessness was motivated by her feelings of love and passion, things intrinsically tied with the Eros instinct. On the other hand, Ursula, the movie's antagonist, encompasses the death instinct. Her life's work revolves around making those around her miserable and almost dead. She seeks souls to capture, driving in people and making deals she knows they won't be able to complete to take their souls and become more powerful. She thrives off death and misery; things tied with the death instinct. 

The absurd man is the one that embraces absurdity; he knows and understands that the world is absurd and does not have a higher meaning, and he lives with the freedom that this thought gives him. Camus states that the "absurd man" seeks acting in order to live through someone else's life. They are not happy enough to simply live their own lives., but instead look to experience and know more about others lives through acting. 

In The Little Mermaid, Ariel does a bit of acting herself. One could argue that her accepting Ursula's deal and gaining legs is in some way acting out someone else's life. Ariel is a mermaid that lives in the sea, meaning that Humans are someone else's reality, one she gets to act as when she washes ashore. This might not be applicable if Ariel, once she gets legs, reveals that she is a mermaid. But instead, because she pretends she has always been a human, she is playing a role and acting to experience someone else's reality. Eventually, of course, the acting comes to a halt once she officially becomes a human. But for the period where she is still under Ursula's contract and is pretending to be someone she is not, she is acting in accordance with Camus and the absurd man.

In Hobbes' Leviathan, Hobbes offers three explanations for the origins of war. Firstly, he states that people fight for gains. He explains that when people look for the same resources as others, it causes conflict. For example, if two people want the same land, conflict and war can come from them fighting to get it. A second cause of war he provides is that people naturally seek safety. If someone feels that something or someone is threatening their safety, they are willing to fight for it. Lastly, Hobbes states that people fight for glory and power. Winning a war can give someone glory, respect, and recognition from others. Additionally, victory can provide them with power from the resources that they gain.

In The Little Mermaid, one can see a few of the origins of war that Hobbes explains. For example, in the ending scenes of the movie Ariel, her father, and everyone fights against Ursula because they want safety, and Ursula is a threat to safety. Although not an outright war, it was a big fight where lives could be potentially lost, and one was; Ursula's. Their reason for entering this "war" was for protection and safety from Ursula, but on the other hand, Ursula's reason for joining this war was glory and resources. Her main objective was to get more and more power and become the most powerful in the sea, giving her both resources and recognition. These encompass two theories of war origins from Hobbes; war for glory and war for resources. 

In Locke's Second Treatise, Locke gives his point of view on the origin of property. He believes that people gain property through their labor and effort. An example he provides is someone picking an apple. He explains that if he picks an apple, it is now his because the labor and energy he spent picking it determines that it is his now. Therefore, his labor and work gained him the right to that property. This reasoning entails that one can gain property without anyone else's agreement.  

In The Little Mermaid, we see Ariel using this definition of property and gaining property. During the character introduction of Ariel, we learn that she scavenges for objects formerly belonging to humans through the ocean, then stores them and keeps them for herself. In her eyes, because she put in the effort to seek these objects, at times facing dangers while doing it and returning them to her place for safekeeping, these objects now belonged to her. On the other hand, Ariel's father, Triton, has no regard for her property, destroying it once he finds out she has it.
