---
title: "newsstory"
format: html
editor: visual
---

## D.C Nightlife: How D.C Residents Navigate Lack of Late-Night Metro

By Paulina Lopez

\*Names and other information removed or changed for privacy reasons.

Metro closing hours might not bother D.C. residents who prefer early nights, but for those who want to storm the dance floor at Decades or listen to late-night live music at Madams Organ, current closing hours mean limited and usually expensive options for getting back home.

Dupont Circle and Adams Morgan are home to many restaurants, bars and clubs. Dupont Circle's New Hampshire Avenue and Adams Morgan's 18th St NW boast locales that fill up with college students and graduates alike looking for a late night out.

D.C Metro runs until midnight Monday through Thursday, until 1 a.m. Fridays and Saturdays, and again until midnight on Sundays. For those who enjoy a late night out, ride request apps like Uber and Lyft have become essential, but at a price.

According to Uber's official website, as ride demand increases, whether because of bad weather, special events, or high demand in the area, the prices for the user go up as well. The same applies to other ride-requesting apps like Lyft.

Dupont Circle and Adams Morgan neighborhoods have many bars, restaurants and clubs near each other. As the night progresses and locales start closing, people nearby each other begin ordering rides, causing price surges.

D.C. resident 27-year-old Macy enjoys going out late at night, frequenting Dupont Circle and Adams Morgan. Her night usually ends between 2 a.m. and 4 a.m., where she said she is left with only an expensive ride back home.

"It's the safest and kind of the only option," Macy said, referencing using apps like Uber and Lyft to get home. "If the metro was open, I would take it home if I'm not alone," Macy said.

Many share Macy's opinion. Although 25-year-old Johns Hopkins graduate student Justin and current D.C. resident decides to drive when going out, he said he still would like the Metro to be open.

"It would be really nice to have the metro open because that's when the most people are out anyway," Justin said.

But not everyone would use Metro services if available. Some have managed to keep expenses low. 21-year-old Colombian Marcos said he would still prefer Uber when coming home late.

"If the Metro was open, I probably would still take Uber. I'm more familiar with Uber," Marcos said.

Although Marcos said there are high costs of ride-requesting apps late at night, he said it isn't an issue for him, who tends to go out with friends and split the costs.

"I'll usually take Uber, especially if I'm by myself. It's not really expensive if I'm going with other people because we usually split the fare," Marcos said.

Whether D.C. residents prefer using the Metro for heading back home during late nights or not, there are several reasons why the Metro closes when it does.

Fynn, former \-\-- and current \-\-\--, explained the reasoning behind Metro's operational hours.

"Generally, the reason Metro has limited evening hours in recent years is because of ongoing overnight maintenance to keep the system in a state of good repair. Crews get a relatively small window of time to do track work, and often the bulk of that time is spent getting people and equipment to work sites, setting up the work zones, doing the work, then tearing down the work site and restoring service in the early morning hours," Fynn sent in an email.

According to Fynn, Metro ran late service in the past, which meant less work time, causing a backlog of work and ultimately inconvenient shutdowns around 2016 and 2017.

Operational logistics is not the only factor responsible for current closing times. Another significant factor is money.

"In the coming year, Metro is also facing a \$750 million budget gap, which, if not filled by local jurisdictional money, will force some hard decisions on service cuts," Fynn sent in an email.

Whether some prefer ride-requesting apps or would like the availability of Metro, late-night hours might not be back soon.
